apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fi8fo7fge-dotnet-basic
  janus-idp.io/tekton: fi8fo7fge-dotnet-basic
  backstage.io/kubernetes-id: fi8fo7fge-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fi8fo7fge-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
